name: iOS build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ios.yml'
      - 'ios/**'
      - 'common/**'
      - 'example/ios/**'
  pull_request:
    paths:
      - '.github/workflows/ios.yml'
      - 'ios/**'
      - 'example/ios/**'
jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          working-directory: example
          bundler-cache: true
      - name: Install dependencies
        run: yarn install
      - name: Install example app dependencies
        run: yarn install
        working-directory: example
      - name: Install pods
        run: bundle exec pod install
        working-directory: example/ios
      - name: Build ios example app
        run: xcodebuild -scheme RNSACExample -workspace RNSACExample.xcworkspace ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator -configuration Debug
        working-directory: example/ios
  ios-build-fabric:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          working-directory: example
          bundler-cache: true
      - name: Install dependencies
        run: yarn install
      - name: Install example app dependencies
        run: yarn install
        working-directory: example
      - name: Install pods for new arch
        run: RCT_NEW_ARCH_ENABLED=1 bundle exec pod install
        working-directory: example/ios
      - name: Build ios example app
        run: xcodebuild -scheme RNSACExample -workspace RNSACExample.xcworkspace ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator -configuration Debug
        working-directory: example/ios
